"""
VibeMe — your own Claude-style coding tutor, powered by the OpenAI API.

Run:
    pip install -r requirements.txt
    export OPENAI_API_KEY=sk-...       (or put it in a .env file)
    export GOOGLE_CLIENT_ID=...        (see README — required for Sign in with Google)
    export FLASK_SECRET_KEY=...        (any random string — keeps logins signed & persistent)
    python app.py

Then open http://localhost:5000

What's new in this version
- Conversations live on the SERVER (SQLite, one file: vibeme.db), tied to the
  Google account. Leave the app, close the tab, switch phones — you come back
  to the same conversation.
- Replies are generated by a background thread, not by the browser connection.
  If you leave mid-answer the reply keeps being written, and when you come back
  the page re-attaches to it and shows the finished (or still-streaming) text.
- File uploads: images, PDFs, Word (.docx) and text/code files.

Note: background generation runs inside the server process, so run ONE process
(python app.py, or e.g. `gunicorn -w 1 --threads 16 app:app`), not many workers.
"""

import hmac
import html
import io
import json
import os
import re
import secrets
import sqlite3
import threading
import time
import uuid
import zipfile
import base64
from contextlib import contextmanager
from datetime import timedelta
from functools import wraps

from flask import (
    Flask, Response, jsonify, render_template, request,
    send_file, session,
)
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token as google_id_token
from openai import OpenAI

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

# Loads a .env file if python-dotenv is installed and a .env exists.
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "dev-secret-change-me")

# "Always remember" logins: sessions are permanent and last 30 days, renewed
# on every request, and the cookie survives the browser closing.
app.config["SESSION_PERMANENT"] = True
app.config["PERMANENT_SESSION_LIFETIME"] = timedelta(days=30)
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"

# Uploads: a single request may carry a file up to MAX_FILE_BYTES.
MAX_FILE_BYTES = 20 * 1024 * 1024          # per file
MAX_ATTACHMENTS_PER_MESSAGE = 8
MAX_TEXT_CHARS = 60_000                     # per text/docx file sent to the model (was 150k = ~37k tokens per turn)
app.config["MAX_CONTENT_LENGTH"] = MAX_FILE_BYTES + 1024 * 1024

@app.before_request
def _make_session_permanent():
    session.permanent = True

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
# Lowest-cost model in ALLOWED_MODELS. Everyone is locked to it unless they unlock
# other models with the secret key (see "Model unlock" below).
DEFAULT_MODEL = os.environ.get("VIBEME_MODEL", "gpt-4.1-mini")
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")

server_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

# Current OpenAI lineup as of late 2026. gpt-5-search-api is the
# Chat-Completions model that always searches the web before replying.
ALLOWED_MODELS = {
    "gpt-6-astra",
    "gpt-5.5",
    "gpt-5.4",
    "gpt-5.4-mini",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-5-search-api",
}
SEARCH_MODELS = {"gpt-5-search-api"}  # searches the web natively and rejects temperature

# --- Token savers ----------------------------------------------------------
MAX_HISTORY_MESSAGES = 6            # only the last 6 messages (3 exchanges) are re-sent each turn
MAX_OUTPUT_TOKENS = 2000            # reply cap on the default (cheap) model
MAX_OUTPUT_TOKENS_UNLOCKED = 4096   # reply cap once a premium model is unlocked

# --- Model unlock ----------------------------------------------------------
# Secret key -> short-lived access code. The key is only ever checked here on the
# server (never put it in chat.js/index.html). Prefer setting VIBEME_MASTER_KEY
# in .env so it isn't stored in the source.
# The code is the SAME for everyone: while one is live, anyone who enters the key
# gets that same code (with the time it has left); when it expires the next
# person to enter the key creates a fresh one. People using their own OpenAI key
# don't need a code at all.
MASTER_KEY = os.environ.get("VIBEME_MASTER_KEY", "FunnyMaster2008")
CODE_TTL_SECONDS = 5 * 60
ACCESS_CODE = {"code": None, "expires": 0.0}   # the one shared code (single process, like ACTIVE_JOBS)
KEY_FAILS = {}                      # user sub -> timestamps of wrong-key attempts
ACCESS_LOCK = threading.Lock()
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"   # no 0/O/1/I so codes are easy to copy


def _same(a, b):
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))


def current_access_code():
    """Returns (code, seconds_left). Makes a new code only if the old one expired."""
    with ACCESS_LOCK:
        t = time.time()
        if not ACCESS_CODE["code"] or ACCESS_CODE["expires"] <= t:
            raw = "".join(secrets.choice(_CODE_ALPHABET) for _ in range(8))
            ACCESS_CODE["code"] = raw[:4] + "-" + raw[4:]
            ACCESS_CODE["expires"] = t + CODE_TTL_SECONDS
        return ACCESS_CODE["code"], max(1, int(ACCESS_CODE["expires"] - t))


def access_code_valid(code):
    code = (code or "").strip().upper()
    with ACCESS_LOCK:
        live = ACCESS_CODE["code"] if ACCESS_CODE["expires"] > time.time() else None
    return bool(code) and bool(live) and _same(live, code)


# This is the heart of VibeMe's personality: a patient, structured human
# teacher who always ships real, runnable code and reaches for a diagram
# whenever a picture would teach faster than a paragraph.
SYSTEM_PROMPT = """You are VibeMe, an expert programmer and patient teacher. Be concise: answer what was asked, no filler, and never restate the question or re-explain code line by line.

TEACHING
- One or two plain-English sentences of "why" first, then the "how" in short numbered steps. Use an everyday analogy only when it really helps. Warm, never condescending.

DIAGRAMS
- Only when structure, flow or sequence truly needs a picture, use a small ```mermaid fenced block. Otherwise skip it.

CODE
- Give complete, correct, runnable code (no pseudocode unless asked). Single snippet: a fenced block with a language tag, e.g. ```python
- Multi-file projects: tag EVERY file's fence with its filename, e.g. ```python name=app.py or ```html name=templates/index.html - the app uses this to build the downloadable project.
- After code, add a brief note on gotchas only. Check imports, names and brackets before answering, and say so if unsure about a library call.

ATTACHMENTS
- Text/code files arrive inside <file name="..."> tags; images and PDFs arrive natively. Refer to them by filename. If asked to change attached code, return only the changed files, each in a ```lang name=path fence.

FORMAT
- Markdown with tight prose. If you used web search, say briefly what was fresh and link the source.
"""


# ---------------------------------------------------------------------------
# Database (SQLite). One small file next to app.py; override with VIBEME_DB.
# ---------------------------------------------------------------------------

DB_PATH = os.environ.get(
    "VIBEME_DB",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "vibeme.db"),
)

# A reply that has been "generating" for this long with no live worker thread
# is considered interrupted (e.g. the server restarted mid-answer).
STALE_AFTER_SECONDS = 120
STREAM_MAX_SECONDS = 20 * 60

ACTIVE_JOBS = set()          # ids of assistant messages being written right now
ACTIVE_LOCK = threading.Lock()
CANCELLED = set()            # ids of assistant messages whose reply was unsent mid-generation


@contextmanager
def db():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db():
    with db() as c:
        c.execute("PRAGMA journal_mode=WAL")
        c.executescript(
            """
            CREATE TABLE IF NOT EXISTS conversations (
                id          TEXT PRIMARY KEY,
                user_sub    TEXT NOT NULL,
                title       TEXT NOT NULL DEFAULT '',
                created_at  REAL NOT NULL,
                updated_at  REAL NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_conv_user ON conversations(user_sub, updated_at DESC);

            CREATE TABLE IF NOT EXISTS messages (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                conversation_id TEXT NOT NULL,
                role            TEXT NOT NULL,
                content         TEXT NOT NULL DEFAULT '',
                status          TEXT NOT NULL DEFAULT 'done',   -- done | generating | error
                created_at      REAL NOT NULL,
                updated_at      REAL NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id, id);

            CREATE TABLE IF NOT EXISTS attachments (
                id              TEXT PRIMARY KEY,
                user_sub        TEXT NOT NULL,
                conversation_id TEXT,
                message_id      INTEGER,
                name            TEXT NOT NULL,
                mime            TEXT NOT NULL,
                kind            TEXT NOT NULL,                  -- image | pdf | text | docx
                size            INTEGER NOT NULL,
                data            BLOB NOT NULL,
                text_content    TEXT,
                created_at      REAL NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_att_msg ON attachments(message_id);
            """
        )
        # Files that were uploaded but never sent with a message: clean up after a day.
        c.execute(
            "DELETE FROM attachments WHERE message_id IS NULL AND created_at < ?",
            (time.time() - 86400,),
        )


init_db()


# ---------------------------------------------------------------------------
# Auth (Google Sign-In only — this doubles as both signup and login: the
# first time a Google account signs in it's created, every time after
# that it's just a login. No passwords anywhere in this app.)
# ---------------------------------------------------------------------------

def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("user"):
            return jsonify({"error": "Not signed in."}), 401
        return view(*args, **kwargs)
    return wrapped


def current_sub():
    return session["user"]["sub"]


@app.route("/api/auth/google", methods=["POST"])
def auth_google():
    """Verifies the Google ID token from the Sign in with Google button and
    starts a long-lived session. Works identically for a brand-new account
    (signup) and a returning one (login) — Google tells us which via the
    token, but we don't need to care: we just upsert the session user."""
    if not GOOGLE_CLIENT_ID:
        return jsonify({"error": "Server has no GOOGLE_CLIENT_ID configured. See README."}), 500

    data = request.get_json(force=True)
    credential = data.get("credential", "")
    try:
        info = google_id_token.verify_oauth2_token(
            credential, google_requests.Request(), GOOGLE_CLIENT_ID
        )
    except Exception as exc:
        return jsonify({"error": f"Google sign-in failed: {exc}"}), 401

    session["user"] = {
        "sub": info.get("sub"),
        "email": info.get("email"),
        "name": info.get("name") or info.get("email"),
        "picture": info.get("picture"),
    }
    return jsonify({"user": session["user"]})


@app.route("/api/auth/logout", methods=["POST"])
def auth_logout():
    session.pop("user", None)
    return jsonify({"ok": True})


@app.route("/api/auth/me")
def auth_me():
    return jsonify({"user": session.get("user")})


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template(
        "index.html",
        model=DEFAULT_MODEL,
        allowed_models=sorted(ALLOWED_MODELS),
        google_client_id=GOOGLE_CLIENT_ID,
        user=session.get("user"),
    )


# ---------------------------------------------------------------------------
# Uploads
# ---------------------------------------------------------------------------

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
TEXT_EXTS = {
    ".txt", ".md", ".markdown", ".rst", ".log", ".csv", ".tsv", ".json", ".jsonl",
    ".xml", ".yml", ".yaml", ".toml", ".ini", ".cfg", ".conf", ".sql",
    ".py", ".js", ".jsx", ".mjs", ".ts", ".tsx", ".html", ".htm", ".css", ".scss",
    ".vue", ".svelte", ".php", ".rb", ".go", ".rs", ".java", ".kt", ".swift",
    ".c", ".h", ".cpp", ".hpp", ".cs", ".sh", ".bat", ".ps1", ".r", ".lua", ".dart",
}


def sniff_image(data):
    """Returns the real image mime type from the file's magic bytes (never
    trusts the browser). SVG is deliberately not allowed — it can carry scripts."""
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if data.startswith((b"GIF87a", b"GIF89a")):
        return "image/gif"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "image/webp"
    return None


def docx_to_text(data):
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        info = zf.getinfo("word/document.xml")
        if info.file_size > 30 * 1024 * 1024:
            raise ValueError("Document is too large to read.")
        xml = zf.read("word/document.xml").decode("utf-8", "replace")
    xml = xml.replace("</w:p>", "\n").replace("<w:tab/>", "\t")
    xml = re.sub(r"<w:br[^>]*/>", "\n", xml)
    return html.unescape(re.sub(r"<[^>]+>", "", xml))


def classify_upload(filename, data):
    """Returns (kind, mime, text_content_or_None). Raises ValueError with a
    user-readable message for anything we can't handle."""
    ext = os.path.splitext(filename.lower())[1]

    image_mime = sniff_image(data)
    if image_mime:
        return "image", image_mime, None
    if ext in IMAGE_EXTS:
        raise ValueError("This image is corrupted or not a real PNG/JPEG/WEBP/GIF.")

    if data.startswith(b"%PDF"):
        return "pdf", "application/pdf", None

    if ext == ".docx":
        try:
            text = docx_to_text(data)
        except Exception:
            raise ValueError("Couldn't read this Word file.")
        return "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", text

    if ext in TEXT_EXTS or ext == "":
        if b"\x00" in data[:8192]:
            raise ValueError("This looks like a binary file, not text.")
        return "text", "text/plain", data.decode("utf-8", "replace")

    raise ValueError(
        "Unsupported file type. You can attach images, PDFs, .docx, and text/code files."
    )


def clean_filename(name):
    name = os.path.basename((name or "file").replace("\\", "/"))
    name = re.sub(r"[\x00-\x1f\"<>|]", "", name).strip() or "file"
    return name[:120]


@app.route("/api/upload", methods=["POST"])
@login_required
def upload():
    files = request.files.getlist("files")
    if not files:
        return jsonify({"error": "No file received."}), 400

    sub = current_sub()
    saved, errors = [], []
    for f in files:
        name = clean_filename(f.filename)
        data = f.read()
        if not data:
            errors.append({"name": name, "error": "The file is empty."})
            continue
        if len(data) > MAX_FILE_BYTES:
            errors.append({"name": name, "error": "File is too large (max 20 MB)."})
            continue
        try:
            kind, mime, text = classify_upload(name, data)
        except ValueError as exc:
            errors.append({"name": name, "error": str(exc)})
            continue

        att_id = uuid.uuid4().hex
        with db() as c:
            c.execute(
                "INSERT INTO attachments (id, user_sub, name, mime, kind, size, data, text_content, created_at)"
                " VALUES (?,?,?,?,?,?,?,?,?)",
                (att_id, sub, name, mime, kind, len(data), data, text, time.time()),
            )
        saved.append({"id": att_id, "name": name, "mime": mime, "kind": kind, "size": len(data)})

    status = 200 if saved or not errors else 400
    return jsonify({"attachments": saved, "errors": errors}), status


@app.route("/api/attachments/<att_id>")
@login_required
def get_attachment(att_id):
    with db() as c:
        row = c.execute(
            "SELECT name, mime, kind, data FROM attachments WHERE id=? AND user_sub=?",
            (att_id, current_sub()),
        ).fetchone()
    if not row:
        return jsonify({"error": "Not found."}), 404

    inline = row["kind"] in ("image", "pdf")
    resp = send_file(
        io.BytesIO(row["data"]),
        mimetype=row["mime"] if inline else "application/octet-stream",
        as_attachment=not inline,
        download_name=row["name"],
    )
    resp.headers["X-Content-Type-Options"] = "nosniff"
    resp.headers["Cache-Control"] = "private, max-age=86400"
    return resp


@app.route("/api/attachments/<att_id>", methods=["DELETE"])
@login_required
def delete_attachment(att_id):
    """Removes a file that was uploaded but not sent yet (the ✕ in the composer)."""
    with db() as c:
        c.execute(
            "DELETE FROM attachments WHERE id=? AND user_sub=? AND message_id IS NULL",
            (att_id, current_sub()),
        )
    return jsonify({"ok": True})


# ---------------------------------------------------------------------------
# Conversations
# ---------------------------------------------------------------------------

def now():
    return time.time()


def expire_stale(conn, conv_id):
    """If a reply is stuck in 'generating' with no worker alive (server was
    restarted mid-answer), mark it as interrupted so the UI stops waiting."""
    cutoff = now() - STALE_AFTER_SECONDS
    rows = conn.execute(
        "SELECT id FROM messages WHERE conversation_id=? AND status='generating' AND updated_at<?",
        (conv_id, cutoff),
    ).fetchall()
    for r in rows:
        with ACTIVE_LOCK:
            alive = r["id"] in ACTIVE_JOBS
        if alive:
            continue
        conn.execute(
            "UPDATE messages SET status='error', content=content || ?, updated_at=? WHERE id=?",
            ("\n\n**Error:** This reply was interrupted because the server restarted. Please send your message again.", now(), r["id"]),
        )


def serialize_message(conn, m):
    atts = conn.execute(
        "SELECT id, name, mime, kind, size FROM attachments WHERE message_id=? ORDER BY created_at",
        (m["id"],),
    ).fetchall()
    return {
        "id": m["id"],
        "role": m["role"],
        "content": m["content"],
        "status": m["status"],
        "attachments": [dict(a) for a in atts],
    }


@app.route("/api/conversations")
@login_required
def list_conversations():
    with db() as c:
        rows = c.execute(
            "SELECT c.id, c.title, c.updated_at, "
            "EXISTS(SELECT 1 FROM messages m WHERE m.conversation_id=c.id AND m.status='generating') AS generating "
            "FROM conversations c WHERE c.user_sub=? ORDER BY c.updated_at DESC LIMIT 500",
            (current_sub(),),
        ).fetchall()
    return jsonify({"conversations": [
        {"id": r["id"], "title": r["title"], "updated_at": r["updated_at"], "generating": bool(r["generating"])}
        for r in rows
    ]})


@app.route("/api/conversations/<conv_id>")
@login_required
def get_conversation(conv_id):
    with db() as c:
        conv = c.execute(
            "SELECT id, title, updated_at FROM conversations WHERE id=? AND user_sub=?",
            (conv_id, current_sub()),
        ).fetchone()
        if not conv:
            return jsonify({"error": "Conversation not found."}), 404
        expire_stale(c, conv_id)
        msgs = c.execute(
            "SELECT id, role, content, status FROM messages WHERE conversation_id=? ORDER BY id",
            (conv_id,),
        ).fetchall()
        out = [serialize_message(c, m) for m in msgs]
    return jsonify({"id": conv["id"], "title": conv["title"], "updated_at": conv["updated_at"], "messages": out})


@app.route("/api/conversations/<conv_id>", methods=["DELETE"])
@login_required
def delete_conversation(conv_id):
    sub = current_sub()
    with db() as c:
        if not c.execute("SELECT 1 FROM conversations WHERE id=? AND user_sub=?", (conv_id, sub)).fetchone():
            return jsonify({"ok": True})
        c.execute("DELETE FROM attachments WHERE conversation_id=?", (conv_id,))
        c.execute("DELETE FROM messages WHERE conversation_id=?", (conv_id,))
        c.execute("DELETE FROM conversations WHERE id=?", (conv_id,))
    return jsonify({"ok": True})


@app.route("/api/messages/<int:msg_id>", methods=["DELETE"])
@login_required
def unsend_message(msg_id):
    """Unsend one of your messages, like Claude's edit: the message and everything
    after it (its reply, and any later turns) is removed and any reply still being
    written is stopped. The text and the message's files are handed back so the
    browser can put them in the composer to edit and re-send."""
    with db() as c:
        row = c.execute(
            "SELECT m.conversation_id, m.role, m.content FROM messages m "
            "JOIN conversations cv ON cv.id=m.conversation_id WHERE m.id=? AND cv.user_sub=?",
            (msg_id, current_sub()),
        ).fetchone()
        if not row:
            return jsonify({"error": "Message not found."}), 404
        if row["role"] != "user":
            return jsonify({"error": "Only your own messages can be unsent."}), 400
        conv_id = row["conversation_id"]

        removed = c.execute(
            "SELECT id, status FROM messages WHERE conversation_id=? AND id>=?", (conv_id, msg_id)
        ).fetchall()
        with ACTIVE_LOCK:
            for r in removed:
                if r["status"] == "generating":
                    CANCELLED.add(r["id"])     # generate_reply stops as soon as it sees this

        # The unsent message's files go back to "uploaded, not sent yet" so they can be re-sent.
        kept = [dict(a) for a in c.execute(
            "SELECT id, name, mime, kind, size FROM attachments WHERE message_id=? ORDER BY created_at",
            (msg_id,),
        ).fetchall()]
        c.execute("UPDATE attachments SET message_id=NULL, conversation_id=NULL WHERE message_id=?", (msg_id,))

        later_ids = [r["id"] for r in removed if r["id"] != msg_id]
        if later_ids:
            marks = ",".join("?" * len(later_ids))
            c.execute(f"DELETE FROM attachments WHERE message_id IN ({marks})", later_ids)
        c.execute("DELETE FROM messages WHERE conversation_id=? AND id>=?", (conv_id, msg_id))

        conversation_deleted = not c.execute(
            "SELECT 1 FROM messages WHERE conversation_id=?", (conv_id,)
        ).fetchone()
        if conversation_deleted:
            c.execute("DELETE FROM conversations WHERE id=?", (conv_id,))
        else:
            c.execute("UPDATE conversations SET updated_at=? WHERE id=?", (now(), conv_id))

    return jsonify({"text": row["content"], "attachments": kept, "conversation_deleted": conversation_deleted})


@app.route("/api/conversations", methods=["DELETE"])
@login_required
def delete_all_conversations():
    sub = current_sub()
    with db() as c:
        ids = [r["id"] for r in c.execute("SELECT id FROM conversations WHERE user_sub=?", (sub,)).fetchall()]
        for cid in ids:
            c.execute("DELETE FROM attachments WHERE conversation_id=?", (cid,))
            c.execute("DELETE FROM messages WHERE conversation_id=?", (cid,))
        c.execute("DELETE FROM conversations WHERE user_sub=?", (sub,))
    return jsonify({"ok": True})


@app.route("/api/import", methods=["POST"])
@login_required
def import_local_history():
    """One-time migration of chats that older versions kept in the browser's
    localStorage. Text only (old chats had no attachments)."""
    data = request.get_json(force=True)
    items = (data.get("conversations") or [])[:200]
    sub = current_sub()
    id_map = {}
    with db() as c:
        for old in items:
            msgs = [
                m for m in (old.get("messages") or [])[:2000]
                if m.get("role") in ("user", "assistant") and isinstance(m.get("content"), str)
            ]
            if not msgs:
                continue
            new_id = uuid.uuid4().hex
            updated = float(old.get("updatedAt") or now() * 1000) / 1000.0
            title = str(old.get("title") or "Imported chat")[:80]
            c.execute(
                "INSERT INTO conversations (id, user_sub, title, created_at, updated_at) VALUES (?,?,?,?,?)",
                (new_id, sub, title, updated, updated),
            )
            for m in msgs:
                c.execute(
                    "INSERT INTO messages (conversation_id, role, content, status, created_at, updated_at)"
                    " VALUES (?,?,?,?,?,?)",
                    (new_id, m["role"], m["content"], "done", updated, updated),
                )
            id_map[str(old.get("id"))] = new_id
    return jsonify({"id_map": id_map})


# ---------------------------------------------------------------------------
# Chat: send a message (starts background generation) + stream/re-attach
# ---------------------------------------------------------------------------

def build_history(conn, conv_id, before_msg_id):
    """Rebuilds the OpenAI message list for a conversation from the database.
    To keep token use low it (a) only includes the last MAX_HISTORY_MESSAGES
    messages and (b) only re-sends the files of the MOST RECENT message that had
    attachments; older attachments are replaced by a one-line note."""
    rows = conn.execute(
        "SELECT id, role, content, status FROM messages WHERE conversation_id=? AND id<? ORDER BY id DESC LIMIT ?",
        (conv_id, before_msg_id, MAX_HISTORY_MESSAGES),
    ).fetchall()
    rows = list(reversed(rows))
    if rows and rows[0]["role"] == "assistant":
        rows = rows[1:]             # don't start the window with an orphan reply

    latest_att = conn.execute(
        "SELECT MAX(message_id) FROM attachments WHERE conversation_id=? AND message_id<?",
        (conv_id, before_msg_id),
    ).fetchone()[0]

    history = []
    for m in rows:
        if m["role"] == "assistant":
            if m["status"] == "done" and m["content"].strip():
                history.append({"role": "assistant", "content": m["content"]})
            continue

        atts = conn.execute(
            "SELECT name, mime, kind, data, text_content FROM attachments WHERE message_id=? ORDER BY created_at",
            (m["id"],),
        ).fetchall()
        if not atts:
            history.append({"role": "user", "content": m["content"]})
            continue

        if m["id"] != latest_att:
            names = ", ".join(a["name"] for a in atts)
            note = f"[Earlier attachment(s): {names} - not re-sent to save tokens; ask the user to re-attach if you need them again.]"
            history.append({"role": "user", "content": (note + "\n" + m["content"]).strip()})
            continue

        parts = []
        for a in atts:
            if a["kind"] in ("text", "docx"):
                text = a["text_content"] or ""
                note = ""
                if len(text) > MAX_TEXT_CHARS:
                    text = text[:MAX_TEXT_CHARS]
                    note = "\n[File truncated — it was too long to include in full.]"
                parts.append({"type": "text", "text": f'<file name="{a["name"]}">\n{text}{note}\n</file>'})
            elif a["kind"] == "image":
                b64 = base64.b64encode(a["data"]).decode("ascii")
                parts.append({"type": "image_url", "image_url": {"url": f'data:{a["mime"]};base64,{b64}'}})
            elif a["kind"] == "pdf":
                b64 = base64.b64encode(a["data"]).decode("ascii")
                parts.append({"type": "file", "file": {
                    "filename": a["name"],
                    "file_data": f"data:application/pdf;base64,{b64}",
                }})
        if m["content"].strip():
            parts.append({"type": "text", "text": m["content"]})
        history.append({"role": "user", "content": parts})
    return history


def generate_reply(msg_id, conv_id, client, model, temperature, max_tokens):
    """Runs in a background thread. Writes the growing reply into the database
    so it survives the browser going away; any page can (re)attach to it."""
    with ACTIVE_LOCK:
        ACTIVE_JOBS.add(msg_id)

    text = ""
    status = "done"
    last_flush = 0.0
    try:
        with db() as conn:
            messages = [{"role": "system", "content": SYSTEM_PROMPT}] + build_history(conn, conv_id, msg_id)

        if msg_id in CANCELLED:     # unsent before the request even started
            return
        kwargs = dict(model=model, messages=messages, stream=True, max_completion_tokens=max_tokens)
        if model in SEARCH_MODELS:
            # Search models browse the web natively and don't accept a temperature override.
            kwargs["web_search_options"] = {}
        else:
            kwargs["temperature"] = temperature

        stream = client.chat.completions.create(**kwargs)
        finish = None
        for chunk in stream:
            if msg_id in CANCELLED:     # the message was unsent: stop paying for tokens
                try:
                    stream.close()
                except Exception:
                    pass
                break
            if not chunk.choices:
                continue
            choice = chunk.choices[0]
            if choice.finish_reason:
                finish = choice.finish_reason
            delta = choice.delta
            if delta and delta.content:
                text += delta.content
                t = time.time()
                if t - last_flush >= 0.2:
                    with db() as conn:
                        conn.execute(
                            "UPDATE messages SET content=?, updated_at=? WHERE id=?",
                            (text, t, msg_id),
                        )
                    last_flush = t
        if finish == "length":
            text += '\n\n*(Reply hit the length limit to save tokens - say "continue" and I will pick up from here.)*'
    except Exception as exc:  # surface the error into the saved reply
        text += f"\n\n**Error:** {exc}"
        status = "error"
    finally:
        try:
            if not text.strip():
                text = "*(The model returned an empty reply. Try rephrasing.)*"
            with db() as conn:
                conn.execute(
                    "UPDATE messages SET content=?, status=?, updated_at=? WHERE id=?",
                    (text, status, time.time(), msg_id),
                )
                conn.execute("UPDATE conversations SET updated_at=? WHERE id=?", (time.time(), conv_id))
        finally:
            with ACTIVE_LOCK:
                ACTIVE_JOBS.discard(msg_id)
                CANCELLED.discard(msg_id)


@app.route("/api/chat", methods=["POST"])
@login_required
def chat():
    """Saves the user's message (with any attachments), creates the assistant's
    placeholder reply, starts generating it in the background, and returns
    immediately. The browser then streams it from /api/messages/<id>/stream.

    The browser may send its own API key / temperature per request. A non-default
    model is honoured when a personal API key is sent or with a valid `access_code`;
    otherwise the default (cheapest) model is used and a `notice` is returned.
    """
    data = request.get_json(force=True)
    text = (data.get("text") or "").strip()
    attachment_ids = data.get("attachment_ids") or []
    conv_id = data.get("conversation_id") or None

    if not isinstance(attachment_ids, list) or len(attachment_ids) > MAX_ATTACHMENTS_PER_MESSAGE:
        return jsonify({"error": f"You can attach up to {MAX_ATTACHMENTS_PER_MESSAGE} files per message."}), 400
    if not text and not attachment_ids:
        return jsonify({"error": "Type a message or attach a file."}), 400
    if len(text) > 100_000:
        return jsonify({"error": "That message is too long."}), 400

    user_key = (data.get("api_key") or "").strip()
    sub = current_sub()

    # Everyone gets the cheap default model. Another model is used when the person
    # brings their OWN OpenAI key (they pay, so no limits) or the request carries the
    # current, unexpired access code (see /api/model-access).
    requested = data.get("model") or DEFAULT_MODEL
    model, notice = DEFAULT_MODEL, None
    if requested != DEFAULT_MODEL and requested in ALLOWED_MODELS:
        if user_key or access_code_valid(data.get("access_code")):
            model = requested
        else:
            notice = f"Access code missing or expired - using {DEFAULT_MODEL}. Get a new code in Settings."
    max_tokens = MAX_OUTPUT_TOKENS_UNLOCKED if (user_key or model != DEFAULT_MODEL) else MAX_OUTPUT_TOKENS
    temperature = data.get("temperature")
    temperature = 0.4 if temperature is None else max(0.0, min(1.0, float(temperature)))

    active_client = OpenAI(api_key=user_key) if user_key else server_client
    if active_client is None:
        return jsonify({"error": "No OpenAI API key configured. Add one in Settings, or set OPENAI_API_KEY on the server."}), 500

    t = now()
    with db() as c:
        if conv_id:
            conv = c.execute("SELECT id FROM conversations WHERE id=? AND user_sub=?", (conv_id, sub)).fetchone()
            if not conv:
                return jsonify({"error": "Conversation not found."}), 404
            expire_stale(c, conv_id)
            if c.execute("SELECT 1 FROM messages WHERE conversation_id=? AND status='generating'", (conv_id,)).fetchone():
                return jsonify({"error": "VibeMe is still replying in this chat. Wait for it to finish."}), 409
        else:
            conv_id = uuid.uuid4().hex

        # Only files this user uploaded and hasn't already sent.
        atts = []
        if attachment_ids:
            marks = ",".join("?" * len(attachment_ids))
            atts = c.execute(
                f"SELECT id, name FROM attachments WHERE id IN ({marks}) AND user_sub=? AND message_id IS NULL",
                (*attachment_ids, sub),
            ).fetchall()
            if len(atts) != len(set(attachment_ids)):
                return jsonify({"error": "One of the attached files is no longer available. Please attach it again."}), 400

        is_new = not c.execute("SELECT 1 FROM conversations WHERE id=?", (conv_id,)).fetchone()
        if is_new:
            base = " ".join(text.split()) or (atts[0]["name"] if atts else "New chat")
            title = base[:48] + ("…" if len(base) > 48 else "")
            c.execute(
                "INSERT INTO conversations (id, user_sub, title, created_at, updated_at) VALUES (?,?,?,?,?)",
                (conv_id, sub, title, t, t),
            )
        else:
            c.execute("UPDATE conversations SET updated_at=? WHERE id=?", (t, conv_id))

        cur = c.execute(
            "INSERT INTO messages (conversation_id, role, content, status, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?)",
            (conv_id, "user", text, "done", t, t),
        )
        user_msg_id = cur.lastrowid
        for a in atts:
            c.execute(
                "UPDATE attachments SET message_id=?, conversation_id=? WHERE id=?",
                (user_msg_id, conv_id, a["id"]),
            )
        cur = c.execute(
            "INSERT INTO messages (conversation_id, role, content, status, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?)",
            (conv_id, "assistant", "", "generating", t, t),
        )
        assistant_msg_id = cur.lastrowid
        user_msg = serialize_message(c, {"id": user_msg_id, "role": "user", "content": text, "status": "done"})

    threading.Thread(
        target=generate_reply,
        args=(assistant_msg_id, conv_id, active_client, model, temperature, max_tokens),
        daemon=True,
    ).start()

    return jsonify({
        "conversation_id": conv_id,
        "user_message": user_msg,
        "assistant_message_id": assistant_msg_id,
        "model_used": model,
        "notice": notice,
    })


@app.route("/api/model-access", methods=["POST"])
@login_required
def model_access():
    """Trade the secret key for the current access code (shared by everyone; lives
    CODE_TTL_SECONDS). The browser attaches the code to each question."""
    data = request.get_json(force=True)
    key = (data.get("key") or "").strip()
    sub = current_sub()
    t = time.time()

    with ACCESS_LOCK:
        fails = [x for x in KEY_FAILS.get(sub, []) if t - x < 600]
        KEY_FAILS[sub] = fails
        if len(fails) >= 5:
            return jsonify({"error": "Too many wrong keys. Try again in 10 minutes."}), 429

    if not MASTER_KEY or not _same(key, MASTER_KEY):
        with ACCESS_LOCK:
            KEY_FAILS.setdefault(sub, []).append(t)
        return jsonify({"error": "Wrong secret key."}), 403

    with ACCESS_LOCK:
        KEY_FAILS.pop(sub, None)
    code, left = current_access_code()
    return jsonify({"code": code, "expires_in": left})


@app.route("/api/messages/<int:msg_id>/stream")
@login_required
def stream_message(msg_id):
    """Server-Sent Events tail of a reply. `offset` is how many characters the
    page already has, so a page that left and came back only receives the rest.
    Closing this connection does NOT stop the reply — it keeps being written."""
    try:
        offset = max(0, int(request.args.get("offset", 0)))
    except ValueError:
        offset = 0

    with db() as c:
        owned = c.execute(
            "SELECT m.conversation_id FROM messages m JOIN conversations cv ON cv.id=m.conversation_id "
            "WHERE m.id=? AND cv.user_sub=?",
            (msg_id, current_sub()),
        ).fetchone()
    if not owned:
        return jsonify({"error": "Not found."}), 404
    conv_id = owned["conversation_id"]

    def generate():
        sent = offset
        deadline = time.time() + STREAM_MAX_SECONDS
        last_ping = time.time()
        while time.time() < deadline:
            with db() as conn:
                expire_stale(conn, conv_id)
                m = conn.execute("SELECT content, status FROM messages WHERE id=?", (msg_id,)).fetchone()
            if m is None:  # conversation was deleted while streaming
                yield f"data: {json.dumps({'done': True})}\n\n"
                return

            content = m["content"]
            if len(content) > sent:
                yield f"data: {json.dumps({'token': content[sent:]})}\n\n"
                sent = len(content)
                last_ping = time.time()

            if m["status"] != "generating":
                yield f"data: {json.dumps({'done': True, 'status': m['status']})}\n\n"
                return

            if time.time() - last_ping > 15:
                yield ": ping\n\n"  # keeps proxies from closing an idle connection
                last_ping = time.time()
            time.sleep(0.15)

    return Response(
        generate(),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.route("/api/zip", methods=["POST"])
@login_required
def make_zip():
    """
    Takes {"project_name": "...", "files": [{"path": "...", "content": "..."}]}
    and returns a downloadable .zip built in memory.
    """
    data = request.get_json(force=True)
    project_name = data.get("project_name") or "vibeme-project"
    files = data.get("files", [])

    if not files:
        return jsonify({"error": "No files to package."}), 400

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in files:
            path = f.get("path", "file.txt").lstrip("/")
            content = f.get("content", "")
            zf.writestr(path, content)
    buffer.seek(0)

    return send_file(
        buffer,
        mimetype="application/zip",
        as_attachment=True,
        download_name=f"{project_name}.zip",
    )


if __name__ == "__main__":
    app.run(debug=True, port=5000, threaded=True)
